source = ~/.config/hypr/mocha.conf

$font = monospace

general {
    hide_cursor = true
}

auth {
    fingerprint {
        enabled = true
        ready_message = Scan fingerprint to unlock
        present_message = Scanning...
        retry_delay = 250 # in milliseconds
    }
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = ~/.config/hypr/wallpaper.jpg
    blur_passes = 1
    blur_size = 0
    noise = 0.0
    brightness = 0.5
    contrast = 1.0
    vibrancy = 0.0
}

input-field {
    monitor =
    size = 16%, 4%
    outline_thickness = 2
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = $blue
    check_color = $blue
    fail_color = $red

    font_color = $text
    fade_on_empty = false
    rounding = 32

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL

    dots_text_format = *
    dots_size = 0.3
    dots_spacing = 0.3

    position = 0, -60
    halign = center
    valign = center
}

# FINGERPRINT
label {
    monitor =
    text = $FPRINTFAIL
    font_size = 12
    font_family = $font

    color = $peach

    position = 0, -120
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME
    font_size = 64
    font_family = $font

    position = 0, 320
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 16
    font_family = $font

    position = 0, 240
    halign = center
    valign = center
}

